# Generated by Django 2.1.4 on 2019-01-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0003_tournament_winning_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winning_team', to='wlct.TournamentTeam'),
        ),
    ]
