# Generated by Django 2.1.4 on 2019-01-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0004_auto_20190123_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
