# Generated by Django 2.1.4 on 2019-04-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0006_tournamentteam_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winning_team', to='wlct.TournamentTeam'),
        ),
    ]
