# Generated by Django 2.1.4 on 2019-04-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0007_auto_20190411_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='update_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='games',
            field=models.TextField(blank=True, null=True),
        ),
    ]
