# Generated by Django 2.1.4 on 2019-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0008_auto_20190411_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_creation_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
