# Generated by Django 2.1.4 on 2019-04-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0009_tournament_game_creation_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStageTournamentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=0)),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wlct.TournamentTeam')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wlct.TournamentTeam')),
            ],
        ),
        migrations.AddField(
            model_name='groupstagetournament',
            name='knockout_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wlct.SeededTournament'),
        ),
        migrations.AddField(
            model_name='groupstagetournamentgroup',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.GroupStageTournament'),
        ),
    ]
