# Generated by Django 2.1.4 on 2019-04-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0010_auto_20190423_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobinTournament',
            fields=[
                ('tournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Tournament')),
                ('type', models.CharField(default='Round Robin', max_length=255)),
                ('games_at_once', models.IntegerField(default=2)),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place', to='wlct.TournamentTeam')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='wlct.TournamentTeam')),
            ],
            bases=('wlct.tournament',),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentgroup',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_group', to='wlct.TournamentTeam'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentgroup',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_group', to='wlct.TournamentTeam'),
        ),
        migrations.AddField(
            model_name='groupstagetournamentgroup',
            name='round_robin_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.RoundRobinTournament'),
        ),
    ]
