# Generated by Django 2.1.4 on 2019-04-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0011_auto_20190424_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagetournament',
            name='champion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place', to='wlct.TournamentTeam'),
        ),
        migrations.AlterField(
            model_name='groupstagetournament',
            name='champion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='wlct.TournamentTeam'),
        ),
        migrations.AlterField(
            model_name='groupstagetournament',
            name='champion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='wlct.TournamentTeam'),
        ),
    ]
