# Generated by Django 2.1.4 on 2019-05-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0013_auto_20190516_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentteam',
            old_name='rr_tournament',
            new_name='round_robin_tournament',
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentgroup',
            name='round_robin_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_tournament', to='wlct.RoundRobinTournament'),
        ),
        migrations.AlterField(
            model_name='groupstagetournamentgroup',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_stage_tournament', to='wlct.GroupStageTournament'),
        ),
    ]
