# Generated by Django 2.1.4 on 2019-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0015_roundrobintournament_parent_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='buchholz',
            field=models.IntegerField(default=0),
        ),
    ]
