# Generated by Django 2.1.4 on 2019-05-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0016_tournamentteam_buchholz'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagetournament',
            name='knockout_teams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='games_left',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
