# Generated by Django 2.1.4 on 2019-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0017_auto_20190521_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
