# Generated by Django 2.1.4 on 2019-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0022_auto_20190603_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='max_games_at_once',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
