# Generated by Django 2.1.4 on 2019-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0023_tournamentteam_max_games_at_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytemplaterotation',
            name='type',
            field=models.CharField(blank=True, default='Monthly Template Circuit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotionalrelegationleague',
            name='type',
            field=models.CharField(blank=True, default='Promotion/Relegation League', max_length=255, null=True),
        ),
    ]
