# Generated by Django 2.1.4 on 2019-06-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0024_auto_20190605_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_on_vacation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
