# Generated by Django 2.1.4 on 2019-06-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0025_player_is_on_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytemplaterotationmonth',
            name='id',
        ),
        migrations.AddField(
            model_name='monthlytemplaterotationmonth',
            name='circuit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wlct.MonthlyTemplateRotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlytemplaterotationmonth',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytemplaterotationmonth',
            name='tournamentround_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.TournamentRound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlytemplaterotationmonth',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
