# Generated by Django 2.1.4 on 2019-06-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0026_auto_20190607_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytemplaterotationmonth',
            name='circuit',
        ),
    ]
