# Generated by Django 2.1.4 on 2019-07-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0027_remove_monthlytemplaterotationmonth_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalrelegationleague',
            name='current_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wlct.PromotionalRelegationLeagueSeason'),
        ),
    ]
