# Generated by Django 2.1.4 on 2019-06-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0028_tournamentgameentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgameentry',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_game', to='wlct.TournamentGame'),
        ),
    ]
