# Generated by Django 2.1.4 on 2019-06-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0029_tournamentgameentry_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgameentry',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='wlct.TournamentGame'),
        ),
    ]
