# Generated by Django 2.1.4 on 2019-07-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0030_auto_20190623_1337'),
        ('wlct', '0028_promotionalrelegationleague_current_season'),
    ]

    operations = [
    ]
