# Generated by Django 2.1.4 on 2019-07-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0032_auto_20190710_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgameentry',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='wlct.Tournament'),
        ),
    ]
