# Generated by Django 2.1.4 on 2019-09-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0033_tournamentgameentry_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessGameLog',
            fields=[
                ('logger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Logger')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.TournamentGame')),
            ],
            bases=('wlct.logger',),
        ),
        migrations.CreateModel(
            name='ProcessNewGamesLog',
            fields=[
                ('logger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Logger')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.Tournament')),
            ],
            bases=('wlct.logger',),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
    ]
