# Generated by Django 2.1.4 on 2019-09-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0034_auto_20190903_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgameentry',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_round', to='wlct.TournamentRound'),
        ),
    ]
