# Generated by Django 2.1.4 on 2019-12-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0035_tournamentgameentry_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanLeague',
            fields=[
                ('tournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Tournament')),
                ('type', models.CharField(blank=True, default='Clan League', max_length=255, null=True)),
            ],
            bases=('wlct.tournament',),
        ),
        migrations.CreateModel(
            name='ClanLeagueTournament',
            fields=[
                ('roundrobintournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.RoundRobinTournament')),
            ],
            bases=('wlct.roundrobintournament',),
        ),
        migrations.CreateModel(
            name='DummyTournament',
            fields=[
                ('tournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Tournament')),
            ],
            bases=('wlct.tournament',),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_game_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_log',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
