# Generated by Django 2.1.4 on 2019-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0036_auto_20191202_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetournament',
            name='creation_interval',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
