# Generated by Django 2.1.4 on 2019-12-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0037_clanleaguetournament_creation_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanLeagueDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clanleaguetournament',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.ClanLeagueDivision'),
        ),
    ]
