# Generated by Django 2.1.4 on 2019-12-04 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0038_auto_20191204_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanLeagueDivisionClan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.Clan')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.ClanLeagueDivision')),
            ],
        ),
    ]
