# Generated by Django 2.1.4 on 2019-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0039_clanleaguedivisionclan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_logs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
