# Generated by Django 2.1.4 on 2019-12-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0041_clanleaguedivision_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetournament',
            name='games_start_times',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clanleaguedivision',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.ClanLeague'),
        ),
    ]
