# Generated by Django 2.1.4 on 2019-12-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0042_auto_20191209_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanLeagueTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateid', models.IntegerField(blank=True, default=0, null=True)),
                ('template_settings', models.TextField(blank=True, default='', null=True)),
                ('players_per_team', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
