# Generated by Django 2.1.4 on 2019-12-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0043_clanleaguetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetemplate',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.ClanLeague'),
        ),
    ]
