# Generated by Django 2.1.4 on 2019-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0044_clanleaguetemplate_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clanleaguetemplate',
            name='templateid',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
