# Generated by Django 2.1.4 on 2019-12-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0045_auto_20191213_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='clan_league_clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clan_league_clan', to='wlct.ClanLeagueDivisionClan'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='clan_league_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clan_league_division', to='wlct.ClanLeagueDivision'),
        ),
    ]
