# Generated by Django 2.1.4 on 2019-12-31 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0046_auto_20191229_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetournament',
            name='clan_league_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wlct.ClanLeagueTemplate'),
        ),
    ]
