# Generated by Django 2.1.4 on 2019-12-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0048_clanleague_game_allocation_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleague',
            name='start_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clanleague',
            name='start_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clanleague',
            name='start_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
