# Generated by Django 2.1.4 on 2020-01-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0049_auto_20191231_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='has_had_bye',
            field=models.BooleanField(default=False),
        ),
    ]
