# Generated by Django 2.1.4 on 2020-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0050_tournamentteam_has_had_bye'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='game_boot_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
