# Generated by Django 2.1.4 on 2020-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0051_tournamentgame_game_boot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='current_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentgame',
            name='outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
