# Generated by Django 2.1.4 on 2020-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0052_auto_20200108_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobintournament',
            name='random_teams',
            field=models.BooleanField(default=False),
        ),
    ]
