# Generated by Django 2.1.4 on 2020-01-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0053_roundrobintournament_random_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bot_token',
            field=models.CharField(db_index=True, default='invalid', max_length=34),
        ),
    ]
