# Generated by Django 2.1.4 on 2020-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0054_player_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
