# Generated by Django 2.1.4 on 2020-01-22 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0058_auto_20200120_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeladder',
            name='seconds_banked',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentgame',
            name='game_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 14, 18, 24, 39500)),
        ),
    ]
