# Generated by Django 2.1.4 on 2020-01-22 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0059_auto_20200122_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='game_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 21, 42, 911029)),
        ),
    ]
