# Generated by Django 2.1.4 on 2020-01-28 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0062_auto_20200128_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='game_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 22, 35, 50, 1913, tzinfo=utc)),
        ),
    ]
