# Generated by Django 2.1.4 on 2020-02-01 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0064_auto_20200128_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_run_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='mentioned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
