# Generated by Django 2.1.4 on 2020-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0065_auto_20200201_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
