# Generated by Django 2.1.4 on 2020-02-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0066_tournament_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguedivisionclan',
            name='max_points_possible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clanleaguedivisionclan',
            name='total_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
