# Generated by Django 2.1.4 on 2020-02-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0069_auto_20200217_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to='wlct.DiscordUser'),
        ),
    ]
