# Generated by Django 2.1.4 on 2020-02-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0070_auto_20200217_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='memberid',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='wlct.DiscordUser'),
        ),
    ]
