# Generated by Django 2.1.4 on 2020-02-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0071_auto_20200217_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='discord_id',
        ),
    ]
