# Generated by Django 2.1.4 on 2020-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0072_remove_player_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='link_mention',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='link_mention',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
