# Generated by Django 2.1.4 on 2020-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0073_auto_20200223_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='leave_after_game',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
