# Generated by Django 2.1.4 on 2020-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0074_tournamentteam_leave_after_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='bot_seen',
            field=models.BooleanField(default=False),
        ),
    ]
