# Generated by Django 2.1.4 on 2020-03-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0076_auto_20200305_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionalrelegationleagueseason',
            old_name='parent_tournament',
            new_name='pr_tournament',
        ),
    ]
