# Generated by Django 2.1.4 on 2020-03-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0078_auto_20200318_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromotionalRelegationDivision',
            new_name='PromotionalRelegationLeagueDivision',
        ),
    ]
