# Generated by Django 2.1.4 on 2020-03-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0079_auto_20200318_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentinvite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentinvite',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
