# Generated by Django 2.1.4 on 2020-03-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0081_auto_20200318_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalRelegationLeagueTournament',
            fields=[
                ('roundrobintournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.RoundRobinTournament')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.ClanLeagueDivision')),
            ],
            bases=('wlct.roundrobintournament',),
        ),
    ]
