# Generated by Django 2.1.4 on 2020-03-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0083_auto_20200319_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='players',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
