# Generated by Django 2.1.4 on 2020-03-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0085_auto_20200323_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='no_winning_team_log_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
