# Generated by Django 2.1.4 on 2020-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0086_tournamentgame_no_winning_team_log_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='players',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
