# Generated by Django 2.1.4 on 2020-04-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0088_botlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeLog',
            fields=[
                ('logger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Logger')),
            ],
            bases=('wlct.logger',),
        ),
    ]
