# Generated by Django 2.1.4 on 2020-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0090_auto_20200406_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalrelegationleagueseason',
            name='games_at_once',
            field=models.IntegerField(default=2),
        ),
    ]
