# Generated by Django 2.1.4 on 2020-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0091_promotionalrelegationleagueseason_games_at_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, default='missing no', max_length=64),
        ),
    ]
