# Generated by Django 2.1.4 on 2020-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0092_auto_20200407_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('roles_link', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='template_settings',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
