# Generated by Django 2.1.4 on 2020-04-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0093_auto_20200409_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordServer',
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='last_boot_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
