# Generated by Django 2.1.4 on 2020-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0094_auto_20200413_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='on_vacation',
            field=models.BooleanField(default=False),
        ),
    ]
