# Generated by Django 2.1.4 on 2020-04-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0095_tournamentteam_on_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
