# Generated by Django 2.1.4 on 2020-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0096_tournamentteam_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeladder',
            name='type',
            field=models.CharField(default='Real-Time Ladder', max_length=255),
        ),
    ]
