# Generated by Django 2.1.4 on 2020-04-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0097_realtimeladder_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiDayLadder',
            fields=[
                ('tournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.Tournament')),
            ],
            bases=('wlct.tournament',),
        ),
    ]
