# Generated by Django 2.1.4 on 2020-04-19 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0098_multidayladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeladder',
            name='max_vetoes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='joined_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 15, 58, 22, 235686, tzinfo=utc)),
        ),
    ]
