# Generated by Django 2.1.4 on 2020-04-19 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0099_auto_20200419_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='joined_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
