# Generated by Django 2.1.4 on 2020-04-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0101_discordtournamentupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordtournamentupdate',
            old_name='update',
            new_name='update_text',
        ),
    ]
