# Generated by Django 2.1.4 on 2020-04-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0102_auto_20200419_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobinRandomTeams',
            fields=[
                ('roundrobintournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wlct.RoundRobinTournament')),
            ],
            bases=('wlct.roundrobintournament',),
        ),
    ]
