# Generated by Django 2.1.4 on 2020-04-24 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0105_auto_20200422_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.BigIntegerField(default=0)),
                ('bet_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.TournamentGame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.Player')),
            ],
        ),
        migrations.CreateModel(
            name='BetOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(default='', max_length=255)),
                ('odds', models.IntegerField(default=0)),
                ('last_changed', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='CLOTBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bets', models.BigIntegerField(default=0)),
                ('in_progress_bets', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordChannelCLOTBookLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelid', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('discord_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.DiscordUser')),
            ],
        ),
    ]
