# Generated by Django 2.1.4 on 2020-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0106_bet_betodds_clotbook_discordchannelclotbooklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bankroll',
            field=models.IntegerField(default=100),
        ),
    ]
