# Generated by Django 2.1.4 on 2020-04-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0107_player_bankroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet_created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='betodds',
            old_name='last_changed',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='player',
        ),
        migrations.RemoveField(
            model_name='betodds',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='betodds',
            name='odds',
        ),
        migrations.AddField(
            model_name='bet',
            name='odds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.BetOdds'),
        ),
        migrations.AddField(
            model_name='bet',
            name='players',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='betodds',
            name='american_odds',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='betodds',
            name='decimal_odds',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='betodds',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.TournamentGame'),
        ),
        migrations.AddField(
            model_name='betodds',
            name='gameid',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='betodds',
            name='initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betodds',
            name='probability',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='engine',
            name='update_elo_scores_500',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.TournamentGame'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='gameid',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
    ]
