# Generated by Django 2.1.4 on 2020-04-26 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0109_betodds_sent_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='betodds',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
