# Generated by Django 2.1.4 on 2020-04-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0110_auto_20200426_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlct.Tournament')),
            ],
        ),
    ]
