# Generated by Django 2.1.4 on 2020-04-27 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0111_tournamentadministrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
