# Generated by Django 2.1.4 on 2020-04-28 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0112_auto_20200427_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='memberid',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentgameentry',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
