# Generated by Django 2.1.4 on 2020-04-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0113_auto_20200428_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchanneltournamentlink',
            name='discord_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wlct.DiscordUser'),
        ),
    ]
