# Generated by Django 2.2.4 on 2020-04-30 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0116_auto_20200429_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetGameOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.BigIntegerField(db_index=True, default=0)),
                ('players', models.CharField(default='', max_length=255)),
                ('decimal_odds', models.CharField(default='', max_length=255)),
                ('american_odds', models.CharField(default='', max_length=255)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial', models.BooleanField(default=False)),
                ('probability', models.CharField(default='', max_length=255)),
                ('sent_created_notification', models.BooleanField(default=False)),
                ('sent_finished_notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BetTeamOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(default='', max_length=255)),
                ('decimal_odds', models.FloatField(default=0.0)),
                ('american_odds', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('players_index', models.IntegerField(default=-1)),
                ('bet_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.BetGameOdds')),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='odds',
        ),
        migrations.AddField(
            model_name='bet',
            name='american_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='decimal_odds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bet',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.Player'),
        ),
        migrations.AddField(
            model_name='bet',
            name='wager',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='betting_open',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='BetOdds',
        ),
        migrations.AddField(
            model_name='betgameodds',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.TournamentGame'),
        ),
        migrations.AddField(
            model_name='bet',
            name='current_odds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wlct.BetTeamOdds'),
        ),
    ]
