# Generated by Django 2.2.4 on 2020-04-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0117_auto_20200430_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='winnings',
            field=models.FloatField(default=0.0),
        ),
    ]
