# Generated by Django 2.2.4 on 2020-05-26 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0120_discordchannelclotbooklink_results_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
