# Generated by Django 2.2.4 on 2020-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0121_auto_20200526_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='level',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
