# Generated by Django 2.2.4 on 2020-06-04 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0122_auto_20200602_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='templateid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentgame',
            name='gameid',
            field=models.CharField(db_index=True, default='Invalid game id', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournamentgameentry',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournamentgameentry',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
