# Generated by Django 2.2.4 on 2020-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0125_swisstournament_extra_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betgameodds',
            name='initial',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='betgameodds',
            name='sent_created_notification',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='betgameodds',
            name='sent_finished_notification',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
