# Generated by Django 2.2.4 on 2020-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0126_auto_20200711_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='process_games_since_created',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
