# Generated by Django 2.2.4 on 2020-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0127_tournamentteam_process_games_since_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='all_games_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_cache_dirty',
            field=models.BooleanField(default=True),
        ),
    ]
