# Generated by Django 2.2.4 on 2020-10-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0127_tournamentteam_process_games_since_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetournament',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanleaguetournament',
            name='tournament_team_order',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
