# Generated by Django 3.1.4 on 2021-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0128_auto_20201207_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchanneltournamentlink',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='promotionalrelegationleague',
            name='type',
            field=models.CharField(blank=True, default='Promotional/Relegation League', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
