# Generated by Django 3.1.4 on 2021-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0129_auto_20210110_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaguetournament',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanleaguetournament',
            name='tournament_team_order',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
